// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oxu.Presentation.Context;

#nullable disable

namespace Oxu.Persistance.Migrations
{
    [DbContext(typeof(OxuDbContext))]
    [Migration("20250525135037_askdjajksld")]
    partial class askdjajksld
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oxu.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.CategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoriesTranslations");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.HeadBanner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeadBanners");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.HeadBannerTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HeadBannerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadBannerId");

                    b.ToTable("HeadBannerTranslations");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.NewsAndTag", b =>
                {
                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewsId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TagId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NewsId", "TagId");

                    b.HasIndex("NewsId1");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("NewsAndTag");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.NewsTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageType")
                        .HasColumnType("int");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsTranslations");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Reactions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.TagTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagsTranslations");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Category", b =>
                {
                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Oxu.Domain.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("CategoryTranslationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("CategoryTranslationId");

                            b1.ToTable("CategoriesTranslations");

                            b1.WithOwner()
                                .HasForeignKey("CategoryTranslationId");
                        });

                    b.Navigation("Category");

                    b.Navigation("CreatedAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Oxu.Domain.Entities.HeadBanner", b =>
                {
                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("HeadBannerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("HeadBannerId");

                            b1.ToTable("HeadBanners");

                            b1.WithOwner()
                                .HasForeignKey("HeadBannerId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Oxu.Domain.Entities.HeadBannerTranslation", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.HeadBanner", "HeadBanner")
                        .WithMany("HeadBannerTranslations")
                        .HasForeignKey("HeadBannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("HeadBannerTranslationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("HeadBannerTranslationId");

                            b1.ToTable("HeadBannerTranslations");

                            b1.WithOwner()
                                .HasForeignKey("HeadBannerTranslationId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("HeadBanner");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.News", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("NewsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("NewsId");

                            b1.ToTable("News");

                            b1.WithOwner()
                                .HasForeignKey("NewsId");
                        });

                    b.Navigation("Category");

                    b.Navigation("CreatedAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Oxu.Domain.Entities.NewsAndTag", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oxu.Domain.Entities.News", null)
                        .WithMany("NewsAndTags")
                        .HasForeignKey("NewsId1");

                    b.HasOne("Oxu.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oxu.Domain.Entities.Tag", null)
                        .WithMany("NewsAndTags")
                        .HasForeignKey("TagId1");

                    b.Navigation("News");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.NewsTranslation", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.News", "News")
                        .WithMany("NewsTranslations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("NewsTranslationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("NewsTranslationId");

                            b1.ToTable("NewsTranslations");

                            b1.WithOwner()
                                .HasForeignKey("NewsTranslationId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Reactions", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.News", "News")
                        .WithMany("Reactions")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("ReactionsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("ReactionsId");

                            b1.ToTable("Reactions");

                            b1.WithOwner()
                                .HasForeignKey("ReactionsId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Tag", b =>
                {
                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Oxu.Domain.Entities.TagTranslation", b =>
                {
                    b.HasOne("Oxu.Domain.Entities.Tag", "Tag")
                        .WithMany("Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Oxu.Domain.ValueObjects.CreatedAtVO", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("TagTranslationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("TagTranslationId");

                            b1.ToTable("TagsTranslations");

                            b1.WithOwner()
                                .HasForeignKey("TagTranslationId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.HeadBanner", b =>
                {
                    b.Navigation("HeadBannerTranslations");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.News", b =>
                {
                    b.Navigation("NewsAndTags");

                    b.Navigation("NewsTranslations");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Oxu.Domain.Entities.Tag", b =>
                {
                    b.Navigation("NewsAndTags");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
